#!/usr/bin/env bash
#
# Helios one-command installer (macOS + Linux).
#
#   curl -fsSL https://raw.githubusercontent.com/satvikndxd/helios-ai-command-center/main/install.sh | bash
#
# What it does (no sudo, everything under ~/.helios):
#   1. finds Python >= 3.11 (macOS hint: brew install python@3.12)
#   2. fetches the Helios source (GitHub tarball, or reuses a local checkout)
#   3. creates a private virtualenv and installs dependencies
#   4. installs the `helios` launcher (tui | api | worker | demo | up | down | test)
#   5. seeds the synthetic demo workspaces and prints your API key
#
# Env overrides: HELIOS_HOME (default ~/.helios), HELIOS_SOURCE_DIR (use a
# local checkout instead of downloading), HELIOS_REPO, HELIOS_REF,
# HELIOS_SKIP_DEMO=1.

set -euo pipefail

HELIOS_HOME="${HELIOS_HOME:-$HOME/.helios}"
HELIOS_REPO="${HELIOS_REPO:-satvikndxd/helios-ai-command-center}"
HELIOS_REF="${HELIOS_REF:-main}"
APP_DIR="$HELIOS_HOME/app"
VENV_DIR="$HELIOS_HOME/venv"
BIN_DIR="$HELIOS_HOME/bin"

GREEN=$'\033[32m'; BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; RESET=$'\033[0m'
say()  { printf '%s\n' "${GREEN}${BOLD}◉${RESET} $*"; }
fail() { printf '%s\n' "${RED}✗ $*${RESET}" >&2; exit 1; }

say "Helios — Governed AI Command Center installer"

# -- 1. Python >= 3.11 -----------------------------------------------------
PY=""
for candidate in python3.13 python3.12 python3.11 python3; do
  if command -v "$candidate" >/dev/null 2>&1 \
     && "$candidate" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3,11) else 1)' 2>/dev/null; then
    PY="$(command -v "$candidate")"
    break
  fi
done
if [ -z "$PY" ]; then
  if [ "$(uname -s)" = "Darwin" ]; then
    fail "Python 3.11+ not found. Install it with:  brew install python@3.12"
  fi
  fail "Python 3.11+ not found. Install python3.11 or newer and re-run."
fi
say "Using $("$PY" --version) ($PY)"

# -- 2. Source -------------------------------------------------------------
mkdir -p "$HELIOS_HOME" "$BIN_DIR"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-.}")" 2>/dev/null && pwd || pwd)"
SOURCE_DIR="${HELIOS_SOURCE_DIR:-}"
if [ -z "$SOURCE_DIR" ] && [ -f "$SCRIPT_DIR/src/helios/main.py" ]; then
  SOURCE_DIR="$SCRIPT_DIR"   # running from a checkout / npm package
fi

if [ -n "$SOURCE_DIR" ]; then
  say "Using local source: $SOURCE_DIR"
  rm -rf "$APP_DIR"
  mkdir -p "$APP_DIR"
  # Copy only what the runtime needs (never any local .env or database).
  cp -R "$SOURCE_DIR/src" "$APP_DIR/src"
  cp -R "$SOURCE_DIR/tests" "$APP_DIR/tests" 2>/dev/null || true
  cp -R "$SOURCE_DIR/docs" "$APP_DIR/docs" 2>/dev/null || true
  cp "$SOURCE_DIR"/requirements*.txt "$APP_DIR/" 2>/dev/null || true
  cp "$SOURCE_DIR/README.md" "$APP_DIR/" 2>/dev/null || true
else
  say "Downloading Helios ($HELIOS_REPO@$HELIOS_REF)…"
  command -v curl >/dev/null 2>&1 || fail "curl is required"
  rm -rf "$APP_DIR"
  mkdir -p "$APP_DIR"
  curl -fsSL "https://github.com/$HELIOS_REPO/tarball/$HELIOS_REF" \
    | tar -xz --strip-components=1 -C "$APP_DIR" \
    || fail "download failed — is the repository public and the ref '$HELIOS_REF' valid?"
fi
[ -f "$APP_DIR/src/helios/main.py" ] || fail "source layout unexpected (src/helios missing)"

# -- 3. Virtualenv + dependencies ------------------------------------------
say "Creating virtualenv and installing dependencies (first run takes ~1 min)…"
"$PY" -m venv "$VENV_DIR"
"$VENV_DIR/bin/python" -m pip install --quiet --upgrade pip
"$VENV_DIR/bin/python" -m pip install --quiet -r "$APP_DIR/requirements-dev.txt"

# -- 4. Launcher -----------------------------------------------------------
cat > "$BIN_DIR/helios" << LAUNCHER
#!/usr/bin/env bash
# Helios launcher — generated by install.sh
set -euo pipefail
HELIOS_HOME="$HELIOS_HOME"
export PYTHONPATH="\$HELIOS_HOME/app/src\${PYTHONPATH:+:\$PYTHONPATH}"
export HELIOS_DATABASE_URL="\${HELIOS_DATABASE_URL:-sqlite:///\$HELIOS_HOME/helios.sqlite3}"
PYBIN="\$HELIOS_HOME/venv/bin/python"
PORT="\${HELIOS_PORT:-8000}"
PIDFILE_API="\$HELIOS_HOME/api.pid"
PIDFILE_WORKER="\$HELIOS_HOME/worker.pid"

usage() {
  cat <<'EOF'
helios — Governed AI Command Center

  helios demo            Seed the 3 synthetic workspaces + print an API key
  helios up              Start the API (:8000) and eval worker in the background
  helios down            Stop background API + worker
  helios tui             Open the terminal agent (GOVERNED by default)
  helios api             Run the API in the foreground
  helios worker          Run the evaluation worker in the foreground
  helios test            Run the full offline test suite
  helios update          Re-run the installer (pulls latest main)
  helios <cli args>      Anything else forwards to the Helios CLI
                         (create-api-key, gateway-add, gateway-list, …)

Typical first run:
  helios demo && helios up
  export HELIOS_API_KEY=<key printed by demo>
  helios tui
EOF
}

case "\${1:-help}" in
  tui)     shift; exec "\$PYBIN" -m helios.tui "\$@" ;;
  api)     shift; exec "\$PYBIN" -m uvicorn helios.main:app --port "\$PORT" "\$@" ;;
  worker)  shift; exec "\$PYBIN" -m helios.worker ;;
  demo)    shift; exec "\$PYBIN" -m helios.cli demo ;;
  test)
    # ISOLATED throwaway DB: the suite's teardown drops all tables, so it
    # must never see the live database.
    shift
    TESTDB="\$(mktemp -d)/helios-test.sqlite3"
    exec env HELIOS_DATABASE_URL="sqlite:///\$TESTDB" \
      "\$PYBIN" -m pytest -q "\$HELIOS_HOME/app/tests"
    ;;
  up)
    if [ -f "\$PIDFILE_API" ] && kill -0 "\$(cat "\$PIDFILE_API")" 2>/dev/null; then
      echo "API already running (pid \$(cat "\$PIDFILE_API"))"
    else
      nohup "\$PYBIN" -m uvicorn helios.main:app --port "\$PORT" \
        > "\$HELIOS_HOME/api.log" 2>&1 & echo \$! > "\$PIDFILE_API"
      echo "API started on http://localhost:\$PORT (log: \$HELIOS_HOME/api.log)"
    fi
    if [ -f "\$PIDFILE_WORKER" ] && kill -0 "\$(cat "\$PIDFILE_WORKER")" 2>/dev/null; then
      echo "Worker already running (pid \$(cat "\$PIDFILE_WORKER"))"
    else
      nohup "\$PYBIN" -m helios.worker \
        > "\$HELIOS_HOME/worker.log" 2>&1 & echo \$! > "\$PIDFILE_WORKER"
      echo "Eval worker started (log: \$HELIOS_HOME/worker.log)"
    fi
    ;;
  down)
    for pidfile in "\$PIDFILE_API" "\$PIDFILE_WORKER"; do
      if [ -f "\$pidfile" ]; then
        kill "\$(cat "\$pidfile")" 2>/dev/null || true
        rm -f "\$pidfile"
      fi
    done
    echo "Helios stopped."
    ;;
  update)
    exec bash -c 'curl -fsSL "https://raw.githubusercontent.com/$HELIOS_REPO/main/install.sh" | HELIOS_SKIP_DEMO=1 bash'
    ;;
  help|-h|--help) usage ;;
  *) exec "\$PYBIN" -m helios.cli "\$@" ;;
esac
LAUNCHER
chmod +x "$BIN_DIR/helios"

# Put `helios` on the PATH: prefer an existing writable bin dir.
LINKED=""
for dir in "$HOME/.local/bin" /usr/local/bin /opt/homebrew/bin; do
  if [ -d "$dir" ] && [ -w "$dir" ]; then
    ln -sf "$BIN_DIR/helios" "$dir/helios"
    LINKED="$dir/helios"
    break
  fi
done
if [ -z "$LINKED" ]; then
  mkdir -p "$HOME/.local/bin"
  ln -sf "$BIN_DIR/helios" "$HOME/.local/bin/helios"
  LINKED="$HOME/.local/bin/helios"
fi
say "Launcher installed: $LINKED"
case ":$PATH:" in
  *":$(dirname "$LINKED"):"*) : ;;
  *) printf '%s\n' "${DIM}  Add it to your PATH:  export PATH=\"$(dirname "$LINKED"):\$PATH\"${RESET}" ;;
esac

# -- 5. Demo ---------------------------------------------------------------
if [ "${HELIOS_SKIP_DEMO:-0}" != "1" ]; then
  say "Seeding the synthetic demo (Engineering · Software · Finance)…"
  "$BIN_DIR/helios" demo
fi

printf '\n'
say "Done. Next:"
printf '%s\n' "  ${BOLD}helios up${RESET}      ${DIM}# start API + worker in the background${RESET}"
printf '%s\n' "  ${BOLD}export HELIOS_API_KEY=<key printed above>${RESET}"
printf '%s\n' "  ${BOLD}helios tui${RESET}     ${DIM}# then: /workspace use engineering${RESET}"
